"""initial_schema

Revision ID: 960cc4a33bbe
Revises: 
Create Date: 2025-03-25 22:30:41.540313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960cc4a33bbe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_data', sa.Column('ceo_count', sa.Integer(), nullable=True))
    op.add_column('monthly_data', sa.Column('ceo_cost', sa.Float(), nullable=True))
    op.add_column('parameters', sa.Column('ceo_start_month', sa.Integer(), nullable=True))
    op.add_column('parameters', sa.Column('ceo_salary', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parameters', 'ceo_salary')
    op.drop_column('parameters', 'ceo_start_month')
    op.drop_column('monthly_data', 'ceo_cost')
    op.drop_column('monthly_data', 'ceo_count')
    # ### end Alembic commands ###
