"""CEO YearlySummary

Revision ID: ac4cd06a1538
Revises: 960cc4a33bbe
Create Date: 2025-03-25 22:41:21.799536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4cd06a1538'
down_revision: Union[str, None] = '960cc4a33bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yearly_summaries', sa.Column('ceo_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yearly_summaries', 'ceo_count')
    # ### end Alembic commands ###
